/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.CaixaDAO;
import DAO.QuadrinhoDAO;
import DTO.CaixaDTO;
import DTO.QuadrinhoDTO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuw
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
        tb_caixa();
    }
    
          formAlteraCaixa altera = new formAlteraCaixa();
          quadrinhosCaixa qCaixa = new quadrinhosCaixa();
        
          public void tb_caixa(){ 
          CaixaDAO caixa = new CaixaDAO();
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
          ArrayList<CaixaDTO> lista = caixa.getListaCaixa();
             Object s[] = new Object[2] ;
                for (int i = 0; i < lista.size(); i++) {
                  s[0]=lista.get(i).getId();
                  s[1]=lista.get(i).getNomeCaixa();
                  model.addRow(s); } } 
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        AddCaixa = new javax.swing.JButton();
        AddQuadrinho = new javax.swing.JButton();
        Procurar = new javax.swing.JButton();
        IrCaixa = new javax.swing.JButton();
        AlteraCaixa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Caixas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "ID", "Caixa"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        AddCaixa.setText("Add Caixa");
        AddCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCaixaActionPerformed(evt);
            }
        });

        AddQuadrinho.setText("Add Quadrinho");
        AddQuadrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddQuadrinhoActionPerformed(evt);
            }
        });

        Procurar.setText("Procurar");
        Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcurarActionPerformed(evt);
            }
        });

        IrCaixa.setText("Ir caixa");
        IrCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IrCaixaActionPerformed(evt);
            }
        });

        AlteraCaixa.setText("Alterar Caixa");
        AlteraCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlteraCaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AlteraCaixa)
                                .addGap(18, 18, 18)
                                .addComponent(IrCaixa))
                            .addComponent(AddCaixa))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                                .addComponent(AddQuadrinho)
                                .addGap(18, 18, 18)))
                        .addComponent(Procurar)
                        .addGap(13, 13, 13)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AddCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Procurar)
                    .addComponent(IrCaixa)
                    .addComponent(AddQuadrinho)
                    .addComponent(AlteraCaixa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCaixaActionPerformed
        dispose();
        formAddCaixa cadastrar = new formAddCaixa();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_AddCaixaActionPerformed

    private void IrCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IrCaixaActionPerformed
          
          if(jTable1.getSelectedRow() >= 0) {
              DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
              int row = jTable1.getSelectedRow();
              String caixaNome = model.getValueAt(row, 1).toString();
              String id = model.getValueAt(row, 0).toString();
              
              dispose();
              qCaixa.jLabel2.setText(id);
              qCaixa.jLabel1.setText(caixaNome);
              qCaixa.setVisible(true);
          } else {
              JOptionPane.showMessageDialog(null, "Por favor, selecione um nome");
          }
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setNumRows(0);
        tb_caixa(); 
    }//GEN-LAST:event_IrCaixaActionPerformed

    private void AddQuadrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddQuadrinhoActionPerformed
        dispose();
        formAddQuadrinho cadastrar = new formAddQuadrinho();
        cadastrar.setVisible(true);
    }//GEN-LAST:event_AddQuadrinhoActionPerformed

    private void ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcurarActionPerformed
        dispose();
        procuraQuadrinho procurar = new procuraQuadrinho();
        procurar.setVisible(true);
    }//GEN-LAST:event_ProcurarActionPerformed

    private void AlteraCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlteraCaixaActionPerformed
        
          if(jTable1.getSelectedRow() >= 0) {
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            int row = jTable1.getSelectedRow();
            String caixaNome = model.getValueAt(row, 1).toString();
            String id = model.getValueAt(row, 0).toString();
            
            dispose();
            altera.jLabel6.setText(id);
            altera.jTextField1.setText(caixaNome);
            altera.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um nome");    
            }
     
    }//GEN-LAST:event_AlteraCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCaixa;
    private javax.swing.JButton AddQuadrinho;
    private javax.swing.JButton AlteraCaixa;
    private javax.swing.JButton IrCaixa;
    private javax.swing.JButton Procurar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
